# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('num1', models.FloatField()),
                ('num2', models.FloatField(null=True)),
                ('num3', models.FloatField(null=True)),
                ('total', models.FloatField()),
                ('operator1', models.CharField(choices=[('Withdraw', '+'), ('Deposit', '-')], max_length=10)),
                ('operator2', models.CharField(blank=True, choices=[('Withdraw', '+'), ('Deposit', '-')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
