# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='num2',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='num3',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='operator2',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='operator3',
        ),
    ]
