# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20161027_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operator1',
            field=models.CharField(choices=[('Withdraw', '-'), ('Deposit', '+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operator2',
            field=models.CharField(blank=True, choices=[('Withdraw', '-'), ('Deposit', '+')], max_length=10),
        ),
    ]
