# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20161028_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='num2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='num3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='operator2',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='operator3',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True),
        ),
    ]
