# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20161028_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='num2',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='num3',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='operator2',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='operator3',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operator1',
            field=models.CharField(choices=[('W', 'withdraw'), ('D', 'Deposit')], max_length=1),
        ),
    ]
