# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20161027_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operator2',
            field=models.CharField(blank=True, choices=[('-----', 'None'), ('Withdraw', '-'), ('Deposit', '+')], max_length=10),
        ),
    ]
