# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20161027_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operator2',
            field=models.CharField(blank=True, choices=[('Withdraw', 'Withdraw'), ('Deposit', 'Withdraw')], max_length=10, null=True),
        ),
    ]
