# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20161027_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='num2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operator1',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operator2',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True),
        ),
    ]
