# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_auto_20161027_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='operator3',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-')], max_length=1, null=True),
        ),
    ]
